### PR TITLE
Fixing tor.service starting problem on ArchLinux

### PR DESCRIPTION
**Pull request by AmirrezaFiroozi**
Tor couldn`t be started duo to not having write permisson on /var/log/tor/log
This will fix it.
Getting bridges from ubuntu-ir to reassure users from bridges` source

### CODE REVIEW

**Comment by salmoh** [comment]
Could you tell me why do you start and then stop tor in this commit?

**Comment by AmirrezaFiroozi** [comment]
In the first time when Tor is not started I think the user  'tor' is not created yet.
So , first we start Tor and we know it won't be started duo to /var/log/Tor permission , then we stop it and we give it write permission so that It will work.

**Comment by salmoh** [comment]
Would you please solve merge conflict, so i would be able to merge your commits?

**Comment by salmoh** [comment]
Please, create a branch for your merge requests, to avoid all new commits be considered here.

**Comment by AmirrezaFiroozi** [comment]
Sorry Would you tell me how to solve merge conflict ? I don`t know how to.

**Comment by AmirrezaFiroozi** [comment]
I`m closing this and going to send another pull-request request becasue there are some new changes /

**Comment by salmoh** [comment]
I suppose for your case, you'd better unstage the file causing conflict and then make a new merge request. But, for the next time, make a new branch for each merge request.

**Pull request closed without merging**
